### ISSUE TITLE
성능 최적화

### ISSUE THREAD

**Issue by WooWan** [WooWan/VizBeats#30]
### Completed

- [x] 잦은 리렌더링으로 인한 브라우저 멈춤 개선 (`scripting 성능 335% 증가`)- https://github.com/WooWan/VizBeats/pull/22
- [x]  무거운 3d 모델들로 인해 초기 로딩시간이 지연되는 현상 발생, 이전 페이지에서 3d modeling을 사전 로딩 & 캐싱을 이용하여 /stage를 접속할 때 FCP, TTI를  개선 - https://github.com/WooWan/VizBeats/pull/25/commits/be402512c8412627fa54911d905099f3dd5272f8
- [x] indexed db를 이용하여 audio 요청 시에 중복 네트워크 호출 제거 https://github.com/WooWan/VizBeats/pull/61/commits/abb91c4c14e5c3fd0e94d3bfca6857e236dad4c5
- [x] static 사이즈 최적화
  - [x] 최적화된 오디오 파일 포맷으로 변환하여 사이즈 89% 감소 - https://github.com/WooWan/VizBeats/pull/28
  - [x]   gltfjsx를 사용하여 draco 압축, 매쉬, texture 최적화 => 사이즈 95% 이상 감소 https://github.com/WooWan/VizBeats/pull/67/commits/81fa9923c4a9c689046bc0d9d4ae33d883d53630
  - [x]  JavaScript audio encoding을 통해 음원 다운로드 시, 2분이 걸림,  ffmpeg wasm을 이용하여 음원 인코딩, 다운로드를 하도록 성능 개선 (17배 향상)  https://github.com/WooWan/VizBeats/pull/61

### TODO
- [ ] prisma에서 drizzle또는 kysley로 라이브러리 교체 필요(serverless에서 prisma가 적합하지 않고, edge runtime 작동 x)
- [ ] app router로 점진적으로 마이그레이션, server component, edge rendering을 통해 최적화를 할 수 있는 부분 분석
